### ISSUE TITLE
Issue about the generated occupancy map.

### ISSUE THREAD

**Issue by JeremyLinky** [devendrachaplot/Object-Goal-Navigation#11]
Hey! Thanks for your awesome work here!
I have a question as below:
When I visualize the _agent_view_ and corresponding RGB (from obs) in model. Semantic_Mapping.forward, I found that the generated occupancy map is opposite to the occupancy of the actual scene in RGB. For example, in the figure below, the generated object A in the generated map is on the right side of the agent, while in the real RGB it is on the left. Several other major objects can also be seen from the red two-way arrows.
![a7bfb7d221c46870323ec564a95fd70](https://user-images.githubusercontent.com/50053052/131237177-fd9ac969-ba62-46b1-b3a0-325e58dd1a7d.png)
At first, I thought that after applying the rotated and translated operation behind, this situation would disappear. But when I continue to visualize _translated_, it seems that this situation still exists (shown as below). Can you explain why this is? Thanks!

![75ca50c4e4ed9ff257737ef1d1f8191](https://user-images.githubusercontent.com/50053052/131237230-0e885e15-1a9b-4214-9ce5-eb87fb15d574.png)

**Comment by duxuan321** [comment]
hello, may I ask that, can you get an occupancy map which has the same shape as ground-truth? I mean, besides the problem you mentioned, does semantic mapping module work well?

**Comment by devendrachaplot** [comment]
You just need to flip the visualization vertically. The mapping code logic is correct.
