### ISSUE TITLE
Generating Ground Truth Semantic Map

### ISSUE THREAD

**Issue by zubair-irshad** [devendrachaplot/Object-Goal-Navigation#13]
Great work and thanks for releasing your code. I am currently reproducing the work for MP3D dataset only and would appreciate your responses to the following questions: 

1. Is the ground-truth semantic map for the MP3D environments also available for training our the model solely on MP3D dataset? 

1. A follow-up to the previous question: Any chance you might be releasing the code for generating the ground truth semantic map (referenced here): https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/objectgoal_env.py#L112, for cases where we might generate our own mp3d ground truth semantic map. 

Thanks!

**Comment by yash-goel** [comment]
Hi @zubair-irshad were you able to get a solution for this problem? Thanks.
