### ISSUE TITLE
Visualize Ground Truth Semantic Map

### ISSUE THREAD

**Issue by duxuan321** [devendrachaplot/Object-Goal-Navigation#15]
hi everyone : )
I found the _visualize() in semantic_exp.py is used to render **Predicted** Semantic Map, and it works pretty well.

But how can we get a **Ground Truth** Semantic Map like this? It seems that simply replace **inputs['sem_map_pred']** with **scene_info[floor_idx]['sem_map']**(which means ground truth semantic map in objectgoal_env.py) didn't work well. 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/74605431/147360165-4c19913d-6ec1-43b5-957d-bff86529794c.png">

**Comment by devendrachaplot** [comment]
The ground truth semantic map is stored in the sem_map variable:
https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/objectgoal_env.py#L112
