### ISSUE TITLE
how can i get the gt semantic map with the pose like the observation

### ISSUE THREAD

**Issue by yezo13** [devendrachaplot/Object-Goal-Navigation#16]
Great work! But I would like to ask how to get he gt semantic map with the pose(both rotation and transition) like the observation in the Predicted Semantic Map?

**Comment by devendrachaplot** [comment]
The ground truth semantic map is stored in the sem_map variable:
https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/objectgoal_env.py#L112

You will need to convert the agent poses in the ground truth semantic map coordinate frame for visualization.

**Comment by yezo13** [comment]
您好，我是叶梓豪。我已经收到您的邮件，会尽快回复您。谢谢~

**Comment by leyuan-sun** [comment]
@yezo13 About gibson dataset, in the training, do we need to generate the semantic ply file as input?

**Comment by yezo13** [comment]
您好，我是叶梓豪。我已经收到您的邮件，会尽快回复您。谢谢~
