### ISSUE TITLE
Issues installing detectron 2

### ISSUE THREAD

**Issue by retoc71586** [devendrachaplot/Object-Goal-Navigation#17]
Good evening, I have been trying to follow the installation procedure via the standard instructions but I can not manage to install detectron2 on M1 Mac. 

Did someone succeed in that?

**Comment by hanniakku** [comment]
Maybe this link helps [https://stackoverflow.com/questions/56083725/macos-build-issues-lstdc-not-found-while-building-python-package](url)
After exporting `export MACOSX_DEPLOYMENT_TARGET=10.9` I ran `CC=clang CXX=clang++ ARCHFLAGS="-arch x86_64" python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'` and the installation went through successfully.

**Comment by devendrachaplot** [comment]
Please open this issue on the detectron2 repository.
