### ISSUE TITLE
The datasets gibson_habitat_trainval.zip 11GB were not found

### ISSUE THREAD

**Issue by Xie-Nav** [devendrachaplot/Object-Goal-Navigation#18]
Hello！You wrote in the Readmi that the Gibson datasets can be downloaded at https://github.com/facebookresearch/habitat-lab#scenes-datasets, but there are no such datasets(gibson_habitat_trainval.zip 11GB) in this URL.Where can I get these datasets?

**Comment by devendrachaplot** [comment]
Hi,

You need to fill this form to get the link to the dataset:
https://docs.google.com/forms/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/viewform

**Comment by Xie-Nav** [comment]
> Hi,
> 
> You need to fill this form to get the link to the dataset: https://docs.google.com/forms/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/viewform

I don't have a Google account. Can you give me another address to download this dataset? thank you very much

**Comment by devendrachaplot** [comment]
I do not own the dataset, you will need to email the Gibson team for access to the dataset.

**Comment by xiyu-ljy** [comment]
hello , i cann't connected to the URL of the episode's dataset .Is there any other channel to get it?
