### ISSUE TITLE
Ground truth top view semantic map of the scene 

### ISSUE THREAD

**Issue by Raminmoslemi** [devendrachaplot/Object-Goal-Navigation#8]
I was wondering how I can get the Ground truth top view semantic map for a given scene (last plot in your demo gif)?

**Comment by devendrachaplot** [comment]
The ground truth semantic map is stored in the `sem_map` variable:
https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/objectgoal_env.py#L112
