### ISSUE TITLE
Why is it so assigned here?

### ISSUE THREAD

**Issue by JeremyLinky** [devendrachaplot/Object-Goal-Navigation#9]
Hello, I don't understand that why use 'lmb' to assign a value to full_map directly here? Later 'lmb' will be reassigned for scene e. It makes me confused. Looking forward to your reply! Thanks!

![image](https://user-images.githubusercontent.com/50053052/130409825-8d57ca58-a06e-428b-ae67-a50145300453.png)

**Comment by devendrachaplot** [comment]
Local map boundaries are reassigned for the next step.
